export const CONFIG_KEYS = {
    MODEL_PROVIDER: 'MODEL_PROVIDER',
    MODEL_NAME: 'MODEL_NAME',
    MODEL_BASE_URL: 'MODEL_BASE_URL',
    MODEL_API_KEY: 'MODEL_API_KEY',
    AGENT_WORKSPACE: 'AGENT_WORKSPACE',
    LOG_LEVEL: 'LOG_LEVEL',
} as const;

export const REQUIRED_CONFIG_KEYS = [
    CONFIG_KEYS.MODEL_PROVIDER,
    CONFIG_KEYS.MODEL_NAME,
    CONFIG_KEYS.MODEL_BASE_URL,
    CONFIG_KEYS.MODEL_API_KEY,
] as const;

export type ConfigKey = (typeof CONFIG_KEYS)[keyof typeof CONFIG_KEYS];
